name: Javascript linting

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        default: '20'
      eslint:
        type: boolean
        default: true
      prettier:
        type: boolean
        default: true

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint vue and js files

    strategy:
      fail-fast: false

    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Build javascript assets
        uses: monicahq/workflows/.github/actions/js@v4
        id: js
        with:
          node-version: ${{ inputs.node-version }}
          mock-assets: ${{ inputs.mock-assets }}

      - name: Run eslint
        if: inputs.eslint
        run: ${{ steps.js.outputs.runner }} run lint --fix
      - name: Run prettier
        if: inputs.prettier
        run: ${{ steps.js.outputs.runner }} run format

      - name: Check if there is any file update needed
        run: |
          status=$(git status --porcelain)
          if [ -n "$status" ]; then
            echo -e "Waiting modifications:\n$status"
            echo "::error::Eslint and prettier found fixes. Please run 'yarn run lint' and 'yarn run format' prior to your next commit."
            exit -1
          fi
